version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: form_builder_app
    container_name: form_builder_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: form_builder_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret
    networks:
      - app-network

  node:
    image: node:18
    container_name: react-vite
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: form_builder_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: form_builder_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: form_builder_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
